# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyper-doctor" do
  name "hyper-doctor"
  desc "CLI tool for managing local development environments with Firebase emulators and multi-service orchestration"
  homepage "https://github.com/hyperfluid-solutions/hyper-doctor"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hdr"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_amd64.tar.gz"
      sha256 "b2c28c93141763c90285f3172ed1cfdaa856f4dbc4a63fe3e2fc316a8c246c84"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_arm64.tar.gz"
      sha256 "68fda451b9dc67e87b8488c083f344c090e5001bd29b5338d070b2d3e6bd295b"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_amd64.tar.gz"
      sha256 "a67662ae7f252bcb34616af99eb38ccf5ade0a03163a46fc2350e8cd251d738b"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_arm64.tar.gz"
      sha256 "582d73c7407a5223bbeb7f2eefed758ae1f36b42abf81ad27c0e5f23cbd48c25"
    end
  end

  caveats do
    "hyper-doctor has been installed."
    ""
    "The CLI binary is named 'hdr' (short for hyper-doctor)."
    ""
    "REQUIRED: process-compose must be installed for service orchestration:"
    "  brew install f1bonacc1/tap/process-compose"
    ""
    "Quick start:"
    "  1. Install process-compose (see above)"
    "  2. Create a hyper-doctor.yaml in your project directory"
    "  3. Run: hdr dev up"
    ""
    "For more information, see:"
    "  https://github.com/hyperfluid-solutions/hyper-doctor"
  end

  # No zap stanza required
end
