# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyper-doctor" do
  name "hyper-doctor"
  desc "CLI tool for managing local development environments with Firebase emulators and multi-service orchestration"
  homepage "https://github.com/hyperfluid-solutions/hyper-doctor"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hdr"
  depends_on formula: [
      "f1bonacc1/tap/process-compose",
    ]

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_amd64.tar.gz"
      sha256 "50d8979dac0a1ac2888a6986f6eb606a26011185f6ae7b800acd7a450d12bc47"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_arm64.tar.gz"
      sha256 "8e8e99d7e487d0945582c48c45c3897bb98c4c2a0ba634e0ce959fe05ce6860c"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_amd64.tar.gz"
      sha256 "036a2918e0b9954154a665bb1ff4c1979f07856c6144474dbfac647cddc30ba3"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_arm64.tar.gz"
      sha256 "4a469032b49917cc85a2ce2bed50eeee9f4293148680e4af30d2fea178afa98b"
    end
  end

  caveats do
    "hyper-doctor has been installed."
    ""
    "The CLI binary is named 'hdr' (short for hyper-doctor)."
    ""
    "Quick start:"
    "  1. Create a hyper-doctor.yaml in your project directory"
    "  2. Run: hdr dev up"
    ""
    "For more information, see:"
    "  https://github.com/hyperfluid-solutions/hyper-doctor"
  end

  # No zap stanza required
end
