# This file was generated by GoReleaser. DO NOT EDIT.
cask "hyper-doctor" do
  name "hyper-doctor"
  desc "CLI tool for managing local development environments with Firebase emulators and multi-service orchestration"
  homepage "https://github.com/hyperfluid-solutions/hyper-doctor"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hdr"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_amd64.tar.gz"
      sha256 "80790f0cd66a8b2261d52382683f55a5873393619dfbda2f77a9a9d27d9c5d13"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_darwin_arm64.tar.gz"
      sha256 "350f93eb914b646e406210064c37c9f91aebc5c39ef526ca8365feb1cc70707a"
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_amd64.tar.gz"
      sha256 "50572f84ff1b1df58e494928f67fff317bc972bd48b253e0fc21b69f280c2b81"
    end
    on_arm do
      url "https://storage.googleapis.com/hyper-doctor-releases/hyper-doctor/#{version}/hyper-doctor_#{version}_linux_arm64.tar.gz"
      sha256 "21b13f83c08b9b68ff43bc18d44569856690bdee7547f272582e3dce065cef36"
    end
  end

  caveats do
    "hyper-doctor has been installed."
    ""
    "The CLI binary is named 'hdr' (short for hyper-doctor)."
    ""
    "REQUIRED: process-compose must be installed for service orchestration:"
    "  brew install f1bonacc1/tap/process-compose"
    ""
    "Quick start:"
    "  1. Install process-compose (see above)"
    "  2. Create a hyper-doctor.yaml in your project directory"
    "  3. Run: hdr dev up"
    ""
    "For more information, see:"
    "  https://github.com/hyperfluid-solutions/hyper-doctor"
  end

  # No zap stanza required
end
